# Generated by Django 4.2.11 on 2024-04-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('sujet', models.CharField(max_length=100)),
            ],
        ),
    ]
