# Generated by Django 4.2.11 on 2024-04-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('type_of_education', models.CharField(choices=[('general', 'GENERAL'), ('technique', 'TECHNIQUE')], default='general', max_length=100, verbose_name='Type of Education')),
                ('description', models.TextField(verbose_name='Description')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('school_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('rank', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('company_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('number_of_experiences', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_date', models.DateTimeField()),
                ('project_completed', models.BooleanField(default=True)),
                ('language_of_prog', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language_of_prog', models.CharField(max_length=200)),
            ],
        ),
    ]
