# Generated by Django 4.2.11 on 2024-04-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.FileField(default='', upload_to='service/'),
            preserve_default=False,
        ),
    ]
