# Generated by Django 4.2.11 on 2024-04-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_contact_pays_alter_contact_sujet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='contact',
            name='pays',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sujet',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='education',
            name='country',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='education',
            name='rank',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='education',
            name='school_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='education',
            name='type_of_education',
            field=models.CharField(choices=[('general', 'GENERAL'), ('technique', 'TECHNIQUE')], default='general', max_length=250, verbose_name='Type of Education'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='language_of_prog',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='service',
            name='language_of_prog',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
    ]
